spring.application.name=Practice
spring.jpa.database=mysql
spring.datasource.url=jdbc:mysql://localhost/YOUR_DB
spring.datasource.username=root
spring.datasource.password=YOUR_PASSWORD
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.servlet.context-path=/Practice

